config/routes.rb
Ultracare::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :templates do
    patch :sort, on: :collection
    get :export, on: :member
    post :import, on: :collection
  end

  resources :settings, only: [:edit, :update]
  resources :change_settings, only: [:edit, :update]

  resources :reports, only: [:show, :new, :edit] do
    post :save, on: :collection
    get :print, on: :member
  end
  resources :search_reports, only: [:new, :index]

  resources :referrers, except: [:new, :show, :destroy] do
    post :import, on: :collection
  end
  resources :doctors, except: [:new, :show, :destroy]

  resources :business_analysis, only: [:index]
  resources :business_reports, only: [:new] do
    get :print, on: :collection
  end

  get :get_help, to: 'home#get_help'
  get :license, to: 'home#license'
  get :features, to: 'home#software_features'
  get :team, to: 'home#team'

  root 'home#index'

end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :report_title %>
    <%= f.input :content, as: :ckeditor, :input_html => { :ckeditor => { :height => 500 } } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing Templates</h1>

<table id='sortable'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Template name</th>
      <th>Report title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.id %></td>
        <td><%= template.name %></td>
        <td><%= template.report_title %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Export', export_template_path(template) %></td>
        <td><%= link_to 'Delete', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new template', new_template_path, class: 'button' %>
<%= link_to 'Export all templates', templates_path(format: 'csv'), class: 'button' %>

<hr/>

<h2>Import Templates</h2>

<%= form_tag import_templates_path, multipart: true do %>
  <%= file_field_tag :file, required: true %>
  <%= submit_tag 'Import', class: 'button' %>
<% end %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Template name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Report title:</strong>
  <%= @template.report_title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @template.content %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>