config/routes.rb
Ultracare::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :templates do
    patch :sort, on: :collection
    get :export, on: :member
    post :import, on: :collection
  end

  resources :settings, only: [:edit, :update]
  resources :change_settings, only: [:edit, :update]

  resources :reports, only: [:show, :new, :edit] do
    post :save, on: :collection
    get :print, on: :member
  end
  resources :search_reports, only: [:new, :index]

  resources :referrers, except: [:new, :show, :destroy] do
    post :import, on: :collection
  end
  resources :doctors, except: [:new, :show, :destroy]

  resources :business_analysis, only: [:index]
  resources :business_reports, only: [:new] do
    get :print, on: :collection
  end

  get :get_help, to: 'home#get_help'
  get :license, to: 'home#license'
  get :features, to: 'home#software_features'
  get :team, to: 'home#team'

  root 'home#index'

end

app/views/shared/_alert.html.erb
<div class="callout alert">
  <p><i class="fi-alert"></i> <%= flash[:alert] %></p>
</div>

app/views/shared/_footer.html.haml
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p © Carepill Healthcare Technologies, Bangalore, India
      .large-6.columns.text-right
        %ul.menu.simple
          %li= link_to 'Software Features', features_path
          %li= link_to 'Get help', get_help_path
          %li= link_to 'License', license_path

app/views/shared/_navigation.html.haml
.top-bar
  .top-bar-title
    %span{"data-hide-for" => "medium", "data-responsive-toggle" => "responsive-menu"}
      %span.menu-icon.dark{"data-toggle" => ""}
    %strong Ultracare
  #responsive-menu
    .top-bar-right
      %ul.dropdown.menu{"data-dropdown-menu" => ""}
        %li= link_to ' Home', root_path, class: 'fi-home large'
        - unless setting.disable_reports
          %li= link_to ' Reports', new_search_report_path, class: 'fi-list-thumbnails large'
        %li= link_to ' Templates', templates_path, class: 'fi-list-thumbnails large'
        - if setting.enable_accounting?
          %li= link_to ' Business Report', new_business_report_path, class: 'fi-page-export-pdf large'
        %li
          = link_to ' More', '#'
          %ul.menu.vertical
            %li= link_to ' Doctors', doctors_path, class: 'fi-address-book large'
            %li= link_to ' Referrers', referrers_path, class: 'fi-address-book large'
            - unless setting.disable_business_analysis
              %li= link_to ' Business Analysis', business_analysis_index_path(business_analysis: date_range_param_last_month), class: 'fi-graph-pie large'
            %li= link_to ' Settings', edit_setting_path(id: setting.id), class: 'fi-wrench large'
        - if user_signed_in?
          - if current_user.admin?
            %li= link_to ' Admin', rails_admin.dashboard_path, class: 'fi-torso-business large'
          %li= link_to ' Logout', destroy_user_session_path, method: 'delete', class: 'fi-lock large'
        - else
          %li= link_to ' Login', new_user_session_path, class: 'fi-unlock large'

app/views/shared/_notice.html.erb
<div class="callout success">
  <p><i class="fi-check"></i> <%= flash[:notice] %></p>
</div>

app/views/shared/_reports_listing.haml
%table
  %thead
    %tr
      %th Report No.
      - if setting.capture_patient_id?
        %th Patient Id
      %th Patient Name
      %th Age
      %th Sex
      %th Report Status
      - if setting.enable_accounting?
        %th Referred By
        %th Amount Collected
        %th Amount Due
      %th Date
      %th Show
      %th Edit
      %th Print
  %tbody
    - reports.each do |report|
      %tr
        %td= report.id
        - if setting.capture_patient_id?
          %td= report.patient.patient_id
        %td= truncate report.patient.name, length: 18
        %td= report.patient.age
        %td= report.patient.sex
        %td= report.status
        - if setting.enable_accounting?
          %td
            - if report.referrer
              = report.referrer.name
          %td= "Rs. #{report.amount_collected}"
          %td= "Rs. #{report.amount_due}"
        %td= report.created_at
        %td.fi-page.small= link_to " Show", report_path(report)
        %td.fi-page-edit.small= link_to " Edit", edit_report_path(report)
        - if report.is_signed_off?
          %td.fi-print.small= link_to " Print", '#', target: '_blank', 'data-report-id' => report.id, class: 'printLink'
        - else
          %td.fi-print.small.disabled= link_to ' Print', 'javascript:void(0)'

app/views/shared/_side_bar.html.erb
<div class="large-12 medium-4 columns text-center">

  <br/>
  <%= link_to "Whole Abdomen Female", new_report_path(type: 'whole_abdomen_female'), class: 'button secondary'  %>
  <%= link_to "Obstetrics", new_report_path(type: 'obstetric'), class: 'button secondary'  %>
  <%= link_to "Upper Abdomen And Obstetrics", new_report_path(type: 'upper_abdomen_and_obstetric'), class: 'button secondary'  %>
  <%= link_to "Whole Abdomen Male", new_report_path(type: 'whole_abdomen_male'), class: 'button secondary'  %>
  <br/>

  <%= link_to "Follicular Study", new_report_path(type: 'follicular_study'), class: 'button secondary'  %>
  <%= link_to "Lower Abdomen Female", new_report_path(type: 'lower_abdomen_female'), class: 'button secondary'  %>
  <%= link_to "KUB Male", new_report_path(type: 'kub_male'), class: 'button secondary'  %>
  <%= link_to "KUB Female", new_report_path(type: 'kub_female'), class: 'button secondary'  %>
  <br/>

  <%= link_to "Upper Abdomen", new_report_path(type: 'upper_abdomen'), class: 'button secondary'  %>
  <%= link_to "Thyroid Gland", new_report_path(type: 'thyroid_gland'), class: 'button secondary' %>
  <%= link_to "Breast", new_report_path(type: 'breast'), class: 'button secondary'  %>
  <%= link_to "Testis", new_report_path(type: 'testis'), class: 'button secondary'  %>
</div>