config/routes.rb
Ultracare::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :templates do
    patch :sort, on: :collection
    get :export, on: :member
    post :import, on: :collection
  end

  resources :settings, only: [:edit, :update]
  resources :change_settings, only: [:edit, :update]

  resources :reports, only: [:show, :new, :edit] do
    post :save, on: :collection
    get :print, on: :member
  end
  resources :search_reports, only: [:new, :index]

  resources :referrers, except: [:new, :show, :destroy] do
    post :import, on: :collection
  end
  resources :doctors, except: [:new, :show, :destroy]

  resources :business_analysis, only: [:index]
  resources :business_reports, only: [:new] do
    get :print, on: :collection
  end

  get :get_help, to: 'home#get_help'
  get :license, to: 'home#license'
  get :features, to: 'home#software_features'
  get :team, to: 'home#team'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @templates = Template.ordered
    @reports = Report.recent.limit(10).decorate
    @draft_reports = Report.recent.drafts.limit(10).decorate
  end
end

app/views/home/_script.html.erb
<script>
  var url = '<%= print_report_path(flash[:report_id]) %>';
  var wnd = window.open(url);
  wnd.print();
</script>

app/views/home/business_analysis.html.haml
= simple_form_for :search, url: business_analysis_path, method: :get do |f|
  .row.padded-top
    .large-6.columns.text-center
      = f.input :date_range, label: 'Date Range', input_html: { id: 'business-analysis-date-range', value: selected_date_range, placeholder: 'Set date range, Last 30 days selected by default', readonly: true }
    .large-6.columns
      = f.submit 'Show Business Analysis', name: 'find_reports', class: 'button round'

.row.padded-top.padded-bottom
  %h2.text-center
    Total cases found:
    = @reports.count

.row.padded-top.padded-bottom
  #piechart

.row.padded-top.padded-bottom
  #container

= render "chart"

app/views/home/business_analytics.html.haml
= simple_form_for :search, url: business_analytics_path, method: :get do |f|
  .row.padded-top
    .large-6.columns.text-center
      = f.input :date_range, label: 'Date Range', input_html: { id: 'business-analytics-date-range', value: selected_date_range, placeholder: 'Set date range, Last 30 days selected by default', readonly: true }
    .large-6.columns
      = f.submit 'Show Business Analytics', name: 'find_reports', class: 'button round'

.row.padded-top
  %h2.text-center
    Total cases found:
    = @reports.count
.row.padded-top
  = pie_chart @pie_chart_data, {library: {title: 'Doctor wise Business Analysis'}}
.row.padded-top
  = line_chart(@line_chart_data, {library: {hAxis: {title: "Timeline"}, vAxis: {title: "Number of Cases"}, title: 'Case wise Business Analysis'}})

app/views/home/business_report.html.haml
%br
= simple_form_for :search, url: print_business_report_path, method: :get do |f|
  .row
    .large-6.columns
      = f.input :doctor_id, collection: Doctor.all, selected: selected_doctor_id,
        label_method: :doctor_name, label: 'Referred By Doctors (optional)',
        input_html: {multiple: true, 'data-placeholder' => 'Select Doctors', class: 'chosen-select' }
      .hint
        "All doctors" will be set by default if you don't choose any.
  .row
    %br
  .row
    .large-4.columns
      = f.input :date_range, label: 'Date Range', input_html: { id: 'business-report-date-range', value: selected_date_range, placeholder: 'Set date range', readonly: true }
  .row
    .large-4.columns
      = f.submit 'Print Business Report', name: 'find_reports', class: 'button round'

app/views/home/get_help.html.haml
%h1 Get Help
%p
  We are available to help in anyway possible. Once we receive your email we will get back to you fast!
  %br
  Send an email to
  = mail_to 'contact@carepill.in'

%p
  %strong Pro Tips:
  %ul
    %li
      Sync Ultracare Reports folder online with help of OneDrive or such services.
    %li
      Using keyboard instead of mouse makes you go faster. Use
      = link_to 'Vimium Chrome Extension', 'https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en', target: '_blank'
      to speed up your navigation. Once installed press "?" to bring up all the available options. Watch
      = link_to 'this video', 'https://www.youtube.com/watch?v=t67Sn0RGK54', target: '_blank'
      to further understand how Vimium works.

app/views/home/index.html.erb
<h2>Reports</h2>
<ul>
  <% @reports.each do |report| %>
    <li><%= link_to "#{report.patient.name} - #{report.report_type.reportable.class.name}", print_reports_path(report), target: '_blank'  %></li>
  <% end %>
</ul>

app/views/home/index.html.haml
%h1.padded-top Select a new report
.row
  .small-6.columns
    = select_tag :template,
      options_from_collection_for_select(@templates, :id, :name),
      include_blank: true,
      class: 'template-selector'
    .right-align
      = link_to ' Add new template', new_template_path, class: 'fi-plus large'

.row.padded-top
  %ul#templates
    - @templates.each do |template|
      %li{id: "template_#{template.id}"}
        = link_to template.name, new_report_path(template_id: template.id), class: 'button secondary'

%br
%h1 Draft reports
= render partial: 'shared/reports_listing', locals: { reports: @draft_reports }

%h1 Recent reports
= render partial: 'shared/reports_listing', locals: { reports: @reports }
.left-align
  = link_to 'See all reports', new_search_report_path
%br

.text-center
  = link_to('http://www.carepill.in', target: '_blank')do
    = image_tag 'carepill_logo.jpg'

app/views/home/print_business_report.html.haml
.text-center
  %h2 Business Report
  %p= params[:search][:date_range]
%hr

- @reports.group_by(&:doctor).each do |doctor, reports|
  .keep-intact
    %p
      = "Dr. #{doctor.name}"
      = "( #{params[:search][:date_range]} )"
    %p
      %b Summary :
      %br
      = "Total Cases - #{reports.count}"
      - reports.group_by(&:reportable_type).each do |reportable_type, reports|
        %br
        = "#{reportable_type.underscore.titleize} - #{reports.count}"
    %table
      %thead
        %tr
          %th S. No.
          %th Patient Name
          %th Age
          %th Sex
          %th Ultrasound Type
          %th Date
      %tbody
        - reports.each_with_index do |report, index|
          %tr
            %td= index + 1
            %td= report.patient.name
            %td= report.patient.age
            %td= report.patient.sex
            %td= report.report_type.reportable.class.name.underscore.titleize
            %td= report.created_at.strftime("%d / %m / %Y")
    %hr

app/views/home/software_features.html.haml
%h1 Software Features / Roadmap

%p
  %strong Software Features:
  %ul
    %li Installs and works completely offline, no internet no problem!
    %li Create, Update, Print reports
    %li Automated storing reports as PDF in Ultracare Reports folder
    %li Backup reports on cloud
    %li Create and store custom report templates
    %li Search for existing reports
    %li Custom header, footer, signature areas
    %li Create report on business generated from Referrers
    %li Sign off report before printing
    %li Save Doctor against each case
    %li Admin Login for report deletion
    %li Responsive user interface
    %li Works on windows 7 (32 bit), windows 8 (32 bit)
    %li Software installer, updates are provided in a CD

%p
  %strong Roadmap:
  %ul
    %li Display report history
    %li Tagging / Categorization of templates
    %li Store reports being printed as Word Doc
    %li Dicom viewer integration
    %li Importing template from word doc
    %li Windows system tray application to show status of application

app/views/home/team.html.haml
%h1 Team

.row
  .large-3.columns
    = image_tag 'team/abhishek.png'
  .large-9.columns
    %h2 Abhishek Srivastava
    %h4 Product Developer, Business Developer
    %p - Bio -

.row.padded-top
  .large-3.columns
    = image_tag 'team/vishwanath.jpg'
  .large-9.columns
    %h2 Dr. Vishwanath Rs (Radiologist)
    %h4 Product Advisor, Business Developer
    %p - Bio -

.row.padded-top
  .large-3.columns
    = image_tag 'team/rajesh.jpg'
  .large-9.columns
    %h2 Rajesh Kumar
    %h4 Sales and Marketing Lead
    %p - Bio -