config/routes.rb
Ultracare::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :templates do
    patch :sort, on: :collection
    get :export, on: :member
    post :import, on: :collection
  end

  resources :settings, only: [:edit, :update]
  resources :change_settings, only: [:edit, :update]

  resources :reports, only: [:show, :new, :edit] do
    post :save, on: :collection
    get :print, on: :member
  end
  resources :search_reports, only: [:new, :index]

  resources :referrers, except: [:new, :show, :destroy] do
    post :import, on: :collection
  end
  resources :doctors, except: [:new, :show, :destroy]

  resources :business_analysis, only: [:index]
  resources :business_reports, only: [:new] do
    get :print, on: :collection
  end

  get :get_help, to: 'home#get_help'
  get :license, to: 'home#license'
  get :features, to: 'home#software_features'
  get :team, to: 'home#team'

  root 'home#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  include PgSearch

  belongs_to :referrer
  belongs_to :patient
  belongs_to :doctor
  accepts_nested_attributes_for :patient

  attr_accessor :referrer_name, :save_status

  module Status
    NEW = :new
    DRAFT = :draft
    SIGNED_OFF = :signed_off
  end

  module SaveStatus
    UNSAVED = :unsaved
    SAVING = :saving
    PENDING = :pending
    SAVED = :saved
    SAVE_FAILED = :save_failed
  end

  before_validation :assign_referrer

  validates_presence_of :patient
  validates_presence_of :referrer, if: :accounting_enabled?
  validates_presence_of :referrer_name, if: :accounting_enabled?

  scope :recent, -> { order(created_at: :desc) }
  scope :drafts, -> { where(status: Report::Status::DRAFT) }

  pg_search_scope :search, :against => [:title, :content]

  scope :limit_reports_to_maximum, -> (max_reports) do
    return all unless max_reports
    limit(max_reports)
  end

  scope :belongs_to_referrer, -> (referrer_id) do
    return all unless referrer_id.present?
    where(referrer_id: referrer_id)
  end

  scope :belongs_to_referrers, -> (referrer_ids) do
    return all if referrer_ids.empty?
    where(referrer_id: referrer_ids)
  end

  scope :date_range, -> (date_range) do
    return all unless date_range.present?
    where(created_at: date_range)
  end

  scope :patient_name, -> (patient_name) do
    return all unless patient_name.present?
    joins(:patient).where("patients.name ilike ?", "%#{patient_name}%").references(:patient)
  end

  scope :patient_id, -> (patient_id) do
    return all unless patient_id.present?
    joins(:patient).where("patients.patient_id ilike ?", "%#{patient_id}%").references(:patient)
  end

  def self.save_from(report_params)
    report_id = report_params[:id]
    if report_id.present?
      report = Report.update_from(report_id, report_params)
    else
      report = Report.create_from(report_params)
    end
    report
  end

  def is_signed_off?
    status == Report::Status::SIGNED_OFF.to_s
  end

  def save_file?
    Gem.win_platform?
  end

  # def on_windows?
  #   RbConfig::CONFIG['target_os'] =~ /mswin|mingw/
  # end

  def file_name
    "#{patient.name}-#{patient.age}yr-#{patient.sex}-#{updated_at.strftime('Signed off at %I-%M%P')}"
  end

  def file_path
    date = created_at.strftime("%d-%m-%Y")
    save_dir_path = Pathname.new('C:/Users/Public/Documents/Ultracare Reports').join(date)
    FileUtils::mkdir_p save_dir_path
    save_path = save_dir_path.join("#{file_name}.pdf")
    save_path
  end

  def assign_referrer
    return if referrer_name.blank?
    self.referrer = Referrer.find_or_create_by(name: referrer_name)
  end

  def possible_genders
    [['Male', Patient::Sex::MALE],
     ['Female', Patient::Sex::FEMALE],
     ['Other', Patient::Sex::OTHER]]
  end

  def accounting_enabled?
    Setting.settings.enable_accounting?
  end

  private

  def self.create_from(report_params)
    report = Report.create(report_params)
    if report.persisted?
      report.save_status = Report::SaveStatus::SAVED
    else
      report.save_status = Report::SaveStatus::SAVE_FAILED
    end
    report
  end

  def self.update_from(report_id, report_params)
    report = self.find(report_id)
    if report.update(report_params)
      report.save_status = Report::SaveStatus::SAVED
    else
      report.save_status = Report::SaveStatus::SAVE_FAILED
    end
    report.reload
  end
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
  validates_presence_of :title, :content
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :redirect_to_root, if: -> { setting.disable_reports? }, only: [:index]
  before_action :load_templates, except: [:show, :print]

  def show
    @report = Report.find(params[:id]).decorate
  end

  def new
    template = Template.find(params[:template_id])
    @report = Report.new(title: template.report_title,
                         status: Report::Status::NEW,
                         content: template.content)
    @report.build_patient
  end

  def save
    report = Report.save_from(report_params)
    render json: report.decorate
  end

  def edit
    @report = Report.find(params[:id])
  end

  def print
    @report = Report.find(params[:id]).decorate
    if @report.is_signed_off?
      if @report.save_file?
        render({save_to_file: @report.file_path}.merge(pdf_options(@report.file_name)))
      else
        render pdf_options(@report.file_name)
      end
    else
      redirect_to root_path, alert: 'Please sign off report before printing.'
    end
  end

  private

  def report_params
    params.require(:report).permit(:id,
                                   :doctor_id,
                                   :referrer_name,
                                   :amount_collected,
                                   :amount_due,
                                   :referrers_discount,
                                   :content,
                                   :title,
                                   :status,
                                   patient_attributes: [:id, :name, :age, :sex, :patient_id])
  end

  def pdf_options(file_name)
    { pdf: file_name,
      show_as_html: params[:debug].present?,
      page_size: 'A4',
      layout: 'pdf.html.haml',
      margin: { bottom: setting.footer_margin.to_i,
                top: setting.header_margin.to_i },
      header: { spacing: setting.header_margin.to_i - 5,
                right: 'Page [page] of [topage]',
                html: { template: 'shared/pdf/header.pdf.haml',
                        layout: 'layouts/header.pdf.haml' } },
      footer: { html: { template: 'shared/pdf/footer.pdf.haml',
                        layout: 'layouts/footer.pdf.haml' } } }
  end

  def load_templates
    @templates = Template.all
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def referrer_name(report)
    if report.referrer_name.present?
      report.referrer_name
    elsif report.referrer.present?
      report.referrer.name
    end
  end
end

app/views/reports/_amount_collected_show.html.haml
- if setting.enable_accounting?
  %hr
  .row
    .small-4.columns
      Amount collected:
      = number_to_currency(@report.amount_collected, unit: 'Rs.')
    .small-4.columns
      Amount due:
      = number_to_currency(@report.amount_due, unit: 'Rs.')
    .small-4.columns
      Referrer discount:
      = number_to_currency(@report.referrers_discount, unit: 'Rs.')

app/views/reports/_append_switch_template.html.haml
%hr
.row
  .large-6.columns
    Append template
    = select_tag :template,
      options_from_collection_for_select(@templates, :id, :name),
      include_blank: true,
      class: 'append-template'
  .large-6.columns
    Switch template
    = select_tag :template,
      options_from_collection_for_select(@templates, :id, :name),
      include_blank: true,
      class: 'switch-template'

app/views/reports/_autocomplete_patient_name.html.haml
:javascript
  $(function(){
    var referrerNames = #{Referrer.referrer_names};
    $( "#report_referrer_name" ).autocomplete({
      source: referrerNames,
      change: function(event,ui) {
        var requireReferrer = #{setting.enable_accounting};
        if (requireReferrer && (ui.item==null)) {
            $("#report_referrer_name").val('');
            $("#report_referrer_name").focus();
          }
        }
    });
  });

app/views/reports/_body.haml
%hr
= f.input :content,
  as: :ckeditor,
  label: false,
  input_html: { ckeditor: { height: setting.report_body_height } }
#report-body-height.hide= setting.report_body_height
= f.input :title, as: :hidden
= f.input :id, as: :hidden
= f.input :status, as: :hidden, input_html: { value: Report::Status::DRAFT }
.row.page-extend-alert.hide
  %span.fi-alert
    You might be crossing the first page.
.row
  .small-6.columns
    = f.association :doctor, label_method: :name,  label: 'Reporting doctor'

app/views/reports/_content.html.haml
%h2.padded-top.text-center.report-title
  = @report.title
= @report.content.html_safe

app/views/reports/_cost.html.erb
<div class="row">
  <div class="small-6 columns">
    <label for="">Total amount collected</label>
    <div class="row collapse">
      <div class="small-1 columns">
        <span class="prefix">Rs.</span>
      </div>
      <div class="small-5 columns">
        <%=  f.input :cost, label: false %>
      </div>
      <div class="small-1 columns">
      </div>
    </div>
  </div>
</div>

app/views/reports/_form.html.haml
= simple_form_for @report, url: save_reports_path, method: :post, html: { id: 'auto-save-report' } do |f|
  .form-container
    %h2.text-center.padded-top.report-title{contenteditable: true}= @report.title
    %hr
    = render 'patient', f: f
    = render 'amount_collected', f: f
    = render 'append_switch_template'
    = render 'body', f: f
    = render 'report_status'
    .padded-top
      = f.submit 'Save', class: 'button round'
      = link_to 'Save and Close',
        root_path,
        id: 'save-and-close',
        class: [('hide' if @report.new_record?), 'button', 'round']
      = link_to 'Sign off', '#', id: 'sign-off', class: [('hide' if @report.is_signed_off?), 'button', 'round']
      = link_to 'Print', root_path, id: 'print', class: [('hide' unless @report.is_signed_off?), 'button', 'round']
      - if @report.new_record?
        = link_to 'Cancel', root_path, class: 'cancel-link'

app/views/reports/_patient.html.haml
= f.fields_for :patient do |patient_fields|
  = patient_fields.input :id, as: :hidden
  .row
    .small-6.columns
      = patient_fields.input :name, label: 'Patient Name'
    .small-6.columns
      = f.input :referrer_name,
        label: 'Referred By',
        required: setting.enable_accounting,
        input_html: { value: referrer_name(f.object) }
      - if setting.enable_accounting
        .right-align
          = link_to ' Add new referrer', referrers_path, class: 'fi-plus large'
  .row
    - if setting.capture_patient_id?
      .small-4.columns
        = patient_fields.input :patient_id, label: 'Patient Id'
    .small-4.columns
      %label{for: 'report_patient_attributes_age'} Age
      .row.collapse
        .input-group
          = patient_fields.input :age, label: false, input_html: { class: 'input-group-field' }
          %span.input-group-label years
    .small-4.columns
      = patient_fields.input :sex,
        as: :radio_buttons,
        collection: @report.possible_genders

= render 'autocomplete_patient_name'

app/views/reports/_report_status.html.haml
%hr
.row
  .large-6.columns
    %div#report-number
      - if @report.persisted?
        = "Report no. #{@report.id}"
    %div
      Report status:
      %span#report-status.report-status= @report.status
    %div
      Save status:
      %span#report-save-status
        - if @report.persisted?
          = Report::SaveStatus::SAVED
        - else
          = Report::SaveStatus::UNSAVED
.row.padded-top
  .callout.radius.hiden

app/views/reports/_switch_templates.html.haml
%hr
.row
  .large-6.columns
    Switch template
    = select_tag :template,
      options_from_collection_for_select(@templates, :id, :name),
      include_blank: true,
      class: 'switch-template'

app/views/reports/new.html.erb
<%= render 'form' %>

app/views/reports/print.html.haml
%hr
= render 'shared/pdf/patient'
%hr
= render :partial => 'content'

app/views/reports/print.pdf.haml
= render 'shared/pdf/patient'
%hr
= render 'shared/pdf/reportable'

app/views/reports/show.html.haml
.padded-top
  = link_to 'Edit report', edit_report_path(@report), class: 'button'
  = link_to 'Print report', print_report_path(@report), target: '_blank', class: 'button'
%h1.padded-top.text-center Report
%hr
= render partial: 'shared/pdf/patient'
= render partial: 'amount_collected_show'

%hr
= render partial: 'content'